"""Canonical evidence items generated by code directly from tool outputs.

These are grounded by construction (they are rendered from the tool payloads),
so the evidence panel is trustworthy even if the LLM is unavailable or wrong.
"""
from __future__ import annotations

from src.contracts import EvidenceItem
from src.copilot.policy_engine import PolicyAssessment
from src.copilot.tools import ToolContext


def _money(x) -> str:
    if x is None:
        return "not provided"
    return f"${float(x):,.2f}".replace(".00", "")


def _first_ok(ctx: ToolContext, name: str) -> dict | None:
    for c in ctx.calls:
        if c.name == name:
            return c.output
    return None


def build_evidence(ctx: ToolContext, assessment: PolicyAssessment | None) -> list[EvidenceItem]:
    items: list[EvidenceItem] = []
    add = lambda source, finding, ref=None: items.append(EvidenceItem(source=source, finding=finding, reference=ref))  # noqa: E731

    r = _first_ok(ctx, "get_purchase_request")
    if r and r.get("ok"):
        q = r["request"]
        integ = ", ".join(q.get("requested_integrations") or []) or "none"
        users = q.get("user_count") if q.get("user_count") is not None else "not provided"
        add("get_purchase_request",
            f"{q.get('product_name')} from {q.get('vendor_name')} ({q.get('category')}): annual cost "
            f"{_money(q.get('annual_cost_usd'))}, users {users}, data access '{q.get('data_access_level')}', "
            f"integrations: {integ}, urgency '{q.get('urgency')}'.", r.get("reference"))

    p = _first_ok(ctx, "get_requester_profile")
    if p:
        if p.get("ok"):
            e, m, h = p["employee"], p.get("manager"), p.get("department_head")
            add("get_requester_profile",
                f"Requester {e['name']} ({e['employee_id']}), {e['department']}, {e['level']}; manager "
                f"{m['name'] + ' (' + m['employee_id'] + ')' if m else 'none on file'}; department head "
                f"{h['name'] + ' (' + h['employee_id'] + ')' if h else 'unresolved'}.", p.get("reference"))
            for note in p.get("data_quality_notes", []):
                add("get_requester_profile", f"Data quality: {note}", p.get("reference"))
        else:
            add("get_requester_profile", f"Requester could not be verified: {p.get('error')}", p.get("reference"))

    b = _first_ok(ctx, "check_department_budget")
    if b:
        if b.get("ok"):
            if b.get("within_budget") is None:
                add("check_department_budget", f"{b['department']} available software budget is {_money(b['available_usd'])}; "
                    "fit cannot be evaluated without an annual cost.", b.get("reference"))
            elif b["within_budget"]:
                add("check_department_budget", f"Requested {_money(b['requested_usd'])} is within {b['department']} available "
                    f"budget of {_money(b['available_usd'])} ({_money(b['remaining_after_usd'])} would remain).", b.get("reference"))
            else:
                add("check_department_budget", f"Requested {_money(b['requested_usd'])} exceeds {b['department']} available "
                    f"budget of {_money(b['available_usd'])} by {_money(b['shortfall_usd'])}.", b.get("reference"))
        else:
            add("check_department_budget", f"Budget could not be verified: {b.get('error')}", b.get("reference"))

    s = _first_ok(ctx, "search_existing_software")
    if s and s.get("ok"):
        relevant = [m for m in s.get("matches", []) if m["relation"] != "related_use_case"]
        if not relevant:
            add("search_existing_software", "No approved catalog product from the same vendor or category.", s.get("reference"))
        for m in relevant[:4]:
            add("search_existing_software",
                f"Catalog {m['software_id']} {m['product_name']} ({m['vendor_name']}, {m['category']}) is "
                f"'{m['status']}', scope {m['scope']}, {m['licensed_seats']} seats, {_money(m['annual_cost_usd'])}/yr; "
                f"relation: {m['relation'].replace('_', ' ')}. Notes: {m.get('notes')}.", m.get("reference"))

    v = _first_ok(ctx, "get_vendor_registry_record")
    if v:
        if v.get("ok"):
            x = v["vendor"]
            add("get_vendor_registry_record",
                f"Registry {x['vendor_id']} {x['vendor_name']}: procurement '{x['procurement_status']}', security "
                f"'{x['security_status']}' (review date {x['security_review_date'] or 'none'}), legal terms "
                f"'{x['legal_terms_status']}'.", v.get("reference"))
        else:
            add("get_vendor_registry_record", f"{v.get('error')}.", v.get("reference"))

    k = _first_ok(ctx, "get_vendor_risk_assessment")
    if k:
        if k.get("ok"):
            d = k["data"]
            add("get_vendor_risk_assessment",
                f"Vendor-risk service: risk '{d.get('risk_level')}', security review '{d.get('security_review_status')}' "
                f"(last review {d.get('last_review_date') or 'none'}), processes personal data: "
                f"{d.get('processes_personal_data')}, stores data outside region: {d.get('stores_data_outside_region')}.",
                k.get("reference"))
        else:
            add("get_vendor_risk_assessment",
                f"Vendor-risk service result '{k.get('status')}': {k.get('error')}. Status treated as unverified.",
                k.get("reference"))

    if assessment is not None:
        for h in assessment.rule_hits:
            if h.rule in {"budget_within", "budget_insufficient"}:
                continue  # already covered by the budget tool item
            add("evaluate_procurement_policy", h.finding, h.section)
    return items
